services:
  - type: web
    name: agrotiquiza
    env: python
    region: ohio
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn agrotiquiza.wsgi:application

    envVars:
      - key: PYTHON_VERSION
        value: 3.12

      - key: SECRET_KEY
        generateValue: true

      - key: DEBUG
        value: False

      # Base de datos (Render la creará después)
      - key: DATABASE_URL
        fromDatabase:
          name: agrotiquiza-db
          property: connectionString

      # SMTP Gmail
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false

databases:
  - name: agrotiquiza-db
    plan: free
    region: ohio
    postgresVersion: 16
